# Generated by Django 3.2 on 2022-05-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_niche_finder', '0002_bestsellers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestsellers',
            name='cat_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bestsellers',
            name='cat_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='bestsellers',
            name='cat_parent_id',
            field=models.CharField(max_length=500),
        ),
    ]
