# Generated by Django 3.2 on 2022-05-02 17:59

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_niche_finder', '0003_auto_20220502_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bestsellers',
            old_name='cat_id',
            new_name='best_cat_id',
        ),
        migrations.RenameField(
            model_name='bestsellers',
            old_name='cat_link',
            new_name='best_cat_link',
        ),
        migrations.RenameField(
            model_name='bestsellers',
            old_name='cat_name',
            new_name='best_cat_name',
        ),
        migrations.RenameField(
            model_name='bestsellers',
            old_name='cat_parent_id',
            new_name='best_cat_parent_id',
        ),
        migrations.AlterField(
            model_name='bestsellers',
            name='best_parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='best_children', to='amazon_niche_finder.bestsellers'),
        ),
    ]
