# Generated by Django 3.2 on 2022-05-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_niche_finder', '0007_auto_20220502_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_bestsellers_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='cat_rt_id',
            field=models.IntegerField(null=True),
        ),
    ]
